core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("about/", views.AboutUsView.as_view(), name="about"),
    path("contact/", views.ContactView.as_view(), name="contact"),
    path("case-studies/", views.CaseStudyView.as_view(), name="case_studies"),
]

deff_site_web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include('core.urls', namespace="core")),
    path('admin/', admin.site.urls),
    path("__debug__/", include('debug_toolbar.urls')),
    # path('', include('ocr_app.urls')), #no working
] 

if settings.PRODUCTION:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models/team.py
from utils.model import Model
from django_extensions.db.models import ActivatorModel, TimeStampedModel, TitleSlugDescriptionModel

class Team(ActivatorModel, TimeStampedModel,TitleSlugDescriptionModel, Model):
    class Meta:
        verbose_name_plural="Team members"

templates/base/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required Meta Tags -->
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}" />
    <!-- Flaticon CSS -->
    <link rel="stylesheet" href="{% static 'assets/fonts/flaticon.css' %}" />
    <!-- Boxicons CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/boxicons.min.css' %}" />
    <!-- Owl Carousel CSS -->
    <link
      rel="stylesheet"
      href="{% static 'assets/css/owl.theme.default.min.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'assets/css/owl.carousel.min.css' %}"
    />
    <!-- Magnific Popup CSS -->
    <link
      rel="stylesheet"
      href="{% static 'assets/css/magnific-popup.min.css' %}"
    />
    <!-- Animate Min CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/animate.min.css' %}" />
    <!-- Meanmenu CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/meanmenu.css' %}" />
    <!-- Style CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}" />
    <!-- Responsive CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/responsive.css' %}" />
    <!-- Theme Dark CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/theme-dark.css' %}" />
      <script src="https://www.google.com/recaptcha/enterprise.js?render=6Lf1NwAqAAAAAMVOXAjHHcT1U3VwZw1OeaEQbKdy"></script>



    <title>Deff Software</title>

    <!-- Favicon -->
    <link
      rel="icon"
      type="image/png"
      href="{% static 'assets/img/favicon.png' %}"
    />
  </head>
  <body>
    <!-- Pre Loader -->
    <div class="preloader">
      <div class="d-table">
        <div class="d-table-cell">
          <div class="spinner"></div>
        </div>
      </div>
    </div>
    <!-- End Pre Loader -->

    <!-- Start Navbar Area -->
    <div class="navbar-area">
      <!-- Menu For Mobile Device -->
      <div class="mobile-nav">
        <a href="{% url 'core:home' %}" class="logo">
          <img
            src="{% static 'assets/img/logo/logo1.png' %}"
            class="logo-one"
            alt="Logo"
          />
          <img
            src="{% static 'assets/img/logo/logo2.png' %}"
            class="logo-two"
            alt="Logo"
          />
        </a>
      </div>

      <!-- Menu For Desktop Device -->
      <div class="main-nav">
        <div class="container-fluid">
            <nav class="container-max-2 navbar navbar-expand-md navbar-light ">
                <a class="navbar-brand" href="index.html">
                    <img src="{% static 'assets/img/logo/logo1.png' %}" class="logo-one" alt="Logo">
                    <img src="{% static 'assets/img/logo/logo2.png' %}" class="logo-two" alt="Logo">
                </a>

                <div class="collapse navbar-collapse mean-menu" id="navbarSupportedContent">
                    <ul class="navbar-nav m-auto">
                        <li class="nav-item">
                            <a href="{% url 'core:home' %}" class="nav-link active">
                                Home 
                                <i class='bx bx-plus'></i>
                            </a>
                            {% comment %} <ul class="dropdown-menu">
                                <li class="nav-item">
                                    <a href="{% url 'core:home' %}" class="nav-link active">
                                        Deff Software
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="index-2.html" class="nav-link">
                                        Data Engineering
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="index-3.html" class="nav-link">
                                        Machine Learning
                                    </a>
                                </li>
                            </ul> {% endcomment %}
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'core:about' %}" class="nav-link">
                                Acerca
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                Products 
                                <i class='bx bx-plus'></i>
                            </a>
                            <ul class="dropdown-menu">
                                <li class="nav-item">
                                    <a href="{% url 'core:case_studies' %}" class="nav-link">
                                        Pharmsyn 
                                    </a>
                                </li>
                                {% comment %} <li class="nav-item">
                                    <a href="service-details.html" class="nav-link">
                                        Service Details 
                                    </a>
                                </li> {% endcomment %}
                            </ul>
                        </li>

                        
                        <li class="nav-item">
                            <a href="{% url 'core:contact' %}" class="nav-link">
                                Contact
                            </a>
                        </li>
                    </ul>

                    <div class="side-nav d-in-line align-items-center">
                        <div class="side-item">
                            <div class="search-box">
                                <i class="flaticon-loupe"></i>
                            </div>
                        </div>

                        {% comment %} <div class="side-item">
                            <div class="user-btn">
                                <a href="#">
                                    <i class="flaticon-contact"></i>
                                </a>
                            </div>
                        </div>

                        <div class="side-item">
                            <div class="nav-add-btn">
                                <a href="#" class="nav-menu-btn">
                                    Contact us 
                                    <i class='bx bx-plus'></i>
                                </a>
                            </div>
                        </div> {% endcomment %}
                    </div>
                </div>
            </nav>
        </div>
    </div>

    <div class="side-nav-responsive">
        <div class="container">
            <div class="dot-menu">
                <div class="circle-inner">
                    <div class="circle circle-one"></div>
                    <div class="circle circle-two"></div>
                    <div class="circle circle-three"></div>
                </div>
            </div>
            
            <div class="container">
                <div class="side-nav-inner">
                    <div class="side-nav justify-content-center  align-items-center">
                        <div class="side-item">
                            <div class="search-box">
                                <i class="flaticon-loupe"></i>
                            </div>
                        </div>

                        <div class="side-item">
                            <div class="user-btn">
                                <a href="#">
                                    <i class="flaticon-contact"></i>
                                </a>
                            </div>
                        </div>

                        <div class="side-item">
                            <div class="nav-add-btn">
                                <a href="#" class="nav-menu-btn border-radius">
                                    Contact us 
                                    <i class='bx bx-plus'></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
    <!-- End Navbar Area -->

    {% block content %} {% endblock %}

    <footer class="footer-area footer-bg pt-100 pb-70">
      <div class="container">
        <div class="footer-top">
          <div class="row align-items-center">
            <div class="col-lg-6 col-sm-6">
              <div class="footer-img">
                <img
                  src="{% static 'assets/img/logo/logo1.png' %}"
                  class="footer-img1"
                  alt="Images"
                />
                <img
                  src="{% static 'assets/img/logo/logo2.png' %}"
                  class="footer-img2"
                  alt="Images"
                />
              </div>
            </div>

            <div class="col-lg-6 col-sm-6">
              <div class="footer-social-icon">
                <ul class="social-link">
                  <li>
                    <a href="#" target="_blank"
                      ><i class="bx bxl-facebook"></i
                    ></a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>

        <div class="copy-right-area">
          <div class="copy-right-text text-center">
            <p>
              Copyright @DEFF
              <script>
                document.write(new Date().getFullYear());
              </script>
              Ingenieria Software 2. Proyecto Final. Desarrollado por Yonatan J. Condori Pacheco, Luis Barja Silva..
            </p>
          </div>
        </div>
      </div>
    </footer>




<div id="chatContainer" class="chat-container">
  <div id="chatHeader" class="chat-header">
      Chatbot
      <span id="closeChat" class="close-chat" onclick="toggleChatbot()">&times;</span>
  </div>
  <div id="chatMessages" class="chat-messages">
      <!-- Aquí se mostrarán los mensajes del chatbot y del usuario -->
  </div>
  <div class="chat-input">
      <input type="text" id="userInput" placeholder="Escribe tu mensaje..." onkeydown="handleKeyDown(event)">
      <button onclick="sendMessage()">Enviar</button>
  </div>
</div>
<div id="floatingButton" class="floating-button" onclick="toggleChatbot()">
  <span>&#9998;</span>
</div>


    <!-- Jquery Min JS -->
    <script src="{% static 'assets/js/jquery.min.js' %}"></script>
    <!-- Bootstrap Bundle Min JS -->
    <script src="{% static 'assets/js/bootstrap.bundle.min.js' %}"></script>
    <!-- Wow Min JS -->
    <script src="{% static 'assets/js/wow.min.js' %}"></script>
    <!-- Owl Carousel Min JS -->
    <script src="{% static 'assets/js/owl.carousel.min.js' %}"></script>
    <!-- Magnific Popup Min JS -->
    <script src="{% static 'assets/js/jquery.magnific-popup.min.js' %}"></script>
    <!-- Meanmenu JS -->
    <script src="{% static 'assets/js/meanmenu.js' %}"></script>
    <!-- Ajaxchimp Min JS -->
    <script src="{% static 'assets/js/jquery.ajaxchimp.min.js' %}"></script>
    <!-- Form Validator Min JS -->
    <script src="{% static 'assets/js/form-validator.min.js' %}"></script>
    <!-- Contact Form JS -->
    <script src="{% static 'assets/js/contact-form-script.js' %}"></script>
    <!-- Custom JS -->
    <script src="{% static 'assets/js/custom.js' %}"></script>
    <script>
      function onClick(e) {
        e.preventDefault();
        grecaptcha.enterprise.ready(async () => {
          const token = await grecaptcha.enterprise.execute('6Lf1NwAqAAAAAMVOXAjHHcT1U3VwZw1OeaEQbKdy', {action: 'LOGIN'});
        });
      }
    </script>
  </body>
</html>

templates/base/footer.html
<!-- Footer Area -->
<footer class="footer-area footer-bg pt-100 pb-70">
  <div class="container">
    <div class="footer-top">
      <div class="row align-items-center">
        <div class="col-lg-6 col-sm-6">
          <div class="footer-img">
            <img
              src="{% static 'assets/img/logo/logo1.png' %}"
              class="footer-img1"
              alt="Images"
            />
            <img
              src="{% static 'assets/img/logo/logo2.png' %}"
              class="footer-img2"
              alt="Images"
            />
          </div>
        </div>

        <div class="col-lg-6 col-sm-6">
          <div class="footer-social-icon">
            <ul class="social-link">
              <li>
                <a href="#" target="_blank"><i class="bx bxl-facebook"></i></a>
              </li>
              <li>
                <a href="#" target="_blank"><i class="bx bxl-twitter"></i></a>
              </li>
              <li>
                <a href="#" target="_blank"><i class="bx bxl-instagram"></i></a>
              </li>
              <li>
                <a href="#" target="_blank"
                  ><i class="bx bxl-pinterest-alt"></i
                ></a>
              </li>
              <li>
                <a href="#" target="_blank"><i class="bx bxl-youtube"></i></a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <div class="footer-midal pt-45 pb-70">
      <div class="row">
        <div class="col-lg-3 col-sm-5">
          <div class="footer-widget">
            <h3>Services</h3>
            <ul class="footer-list">
              <li>
                <a href="#">International SEO</a>
              </li>
              <li>
                <a href="#">Enterprise SEO</a>
              </li>
              <li>
                <a href="#">SEO for Small Business</a>
              </li>
              <li>
                <a href="#">SEO for Local Services</a>
              </li>
              <li>
                <a href="#">National SEO</a>
              </li>
            </ul>
          </div>
        </div>

        <div class="col-lg-2 col-sm-7">
          <div class="footer-widget">
            <h3>Company</h3>
            <ul class="footer-list">
              <li>
                <a href="#">About the Company</a>
              </li>
              <li>
                <a href="#">For Customers</a>
              </li>
              <li>
                <a href="#">SEO Blog & News</a>
              </li>
              <li>
                <a href="#">Careers & Reviews</a>
              </li>
              <li>
                <a href="#">Sitemap</a>
              </li>
            </ul>
          </div>
        </div>

        <div class="col-lg-3 col-sm-5">
          <div class="footer-widget ps-5">
            <h3>Learning</h3>
            <ul class="footer-list">
              <li>
                <a href="#">About the Company</a>
              </li>
              <li>
                <a href="#">International SEO</a>
              </li>
              <li>
                <a href="#">National SEO</a>
              </li>
              <li>
                <a href="#">Careers & Reviews</a>
              </li>
              <li>
                <a href="#">Sitemap</a>
              </li>
            </ul>
          </div>
        </div>

        <div class="col-lg-4 col-sm-7">
          <div class="footer-widget">
            <h3>Newsletter</h3>
            <p>To get the latest news and latest up- dates from us</p>
            <div class="newsletter-area">
              <form
                class="newsletter-form"
                data-toggle="validator"
                method="POST"
              >
                <input
                  type="email"
                  class="form-control"
                  placeholder="Your Email*"
                  name="EMAIL"
                  required
                  autocomplete="off"
                />
                <button class="default-btn" type="submit">Subscribe</button>
                <div id="validator-newsletter" class="form-result"></div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="copy-right-area">
      <div class="copy-right-text text-center">
        <p>
          Copyright @
          <script>
            document.write(new Date().getFullYear());
          </script>
          Zinka. All Rights Reserved by
          <a href="https://hibootstrap.com/" target="_blank">HiBootstrap</a>
        </p>
      </div>
    </div>
  </div>
</footer>
<!-- Footer Area End -->

templates/base/navbar.html
{% extends "base/base.html" %} {% load static %} 
{% block navbar %}

<!-- Menu For Mobile Device -->
<div class="mobile-nav">
  <a href="index.html" class="logo">
    <img
      src="{% static 'assets/img/logo/logo1.png' %}"
      class="logo-one"
      alt="Logo"
    />
    <img
      src="{% static 'assets/img/logo/logo2.png' %}"
      class="logo-two"
      alt="Logo"
    />
  </a>
</div>

<!-- Menu For Desktop Device -->
<div class="main-nav">
  <div class="container-fluid">
    <nav class="container-max-2 navbar navbar-expand-md navbar-light">
      <a class="navbar-brand" href="index.html">
        <img
          src="{% static 'assets/img/logo/logo1.png' %}"
          class="logo-one"
          alt="Logo"
        />
        <img
          src="{% static 'assets/img/logo/logo2.png' %}"
          class="logo-two"
          alt="Logo"
        />
      </a>

      <div
        class="collapse navbar-collapse mean-menu"
        id="navbarSupportedContent"
      >
        <ul class="navbar-nav m-auto">
          <li class="nav-item">
            <a href="#" class="nav-link active">
              Home
              <i class="bx bx-plus"></i>
            </a>
            <ul class="dropdown-menu">
              <li class="nav-item">
                <a href="index.html" class="nav-link active"> SEO Agency </a>
              </li>
              <li class="nav-item">
                <a href="index-2.html" class="nav-link"> AI Startup </a>
              </li>
              <li class="nav-item">
                <a href="index-3.html" class="nav-link"> Machine Learning </a>
              </li>
            </ul>
          </li>
          <li class="nav-item">
            <a href="about.html" class="nav-link"> About </a>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link">
              Pages
              <i class="bx bx-plus"></i>
            </a>
            <ul class="dropdown-menu">
              <li class="nav-item">
                <a href="team.html" class="nav-link"> Team </a>
              </li>
              <li class="nav-item">
                <a href="pricing.html" class="nav-link"> Pricing Table </a>
              </li>
              <li class="nav-item">
                <a href="faq.html" class="nav-link"> FAQ </a>
              </li>
              <li class="nav-item">
                <a href="#" class="nav-link">
                  Courses
                  <i class="bx bx-plus"></i>
                </a>
                <ul class="dropdown-menu">
                  <li class="nav-item">
                    <a href="courses.html" class="nav-link"> Courses </a>
                  </li>
                  <li class="nav-item">
                    <a href="course-details.html" class="nav-link">
                      Course Details
                    </a>
                  </li>
                </ul>
              </li>
              <li class="nav-item">
                <a href="testimonials.html" class="nav-link"> Testimonials </a>
              </li>
              <li class="nav-item">
                <a href="#" class="nav-link">
                  Case study
                  <i class="bx bx-plus"></i>
                </a>
                <ul class="dropdown-menu">
                  <li class="nav-item">
                    <a href="case-study.html" class="nav-link"> Case study </a>
                  </li>
                  <li class="nav-item">
                    <a href="case-details.html" class="nav-link">
                      Case study Details
                    </a>
                  </li>
                </ul>
              </li>
              <li class="nav-item">
                <a href="404.html" class="nav-link"> 404 page </a>
              </li>
              <li class="nav-item">
                <a href="sign-in.html" class="nav-link"> Sign In </a>
              </li>
              <li class="nav-item">
                <a href="sign-up.html" class="nav-link"> Sign Up </a>
              </li>
              <li class="nav-item">
                <a href="terms-condition.html" class="nav-link">
                  Terms & Conditions
                </a>
              </li>
              <li class="nav-item">
                <a href="privacy-policy.html" class="nav-link">
                  Privacy Policy
                </a>
              </li>
              <li class="nav-item">
                <a href="coming-soon.html" class="nav-link"> Coming Soon </a>
              </li>
            </ul>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link">
              Services
              <i class="bx bx-plus"></i>
            </a>
            <ul class="dropdown-menu">
              <li class="nav-item">
                <a href="services.html" class="nav-link"> Services </a>
              </li>
              <li class="nav-item">
                <a href="service-details.html" class="nav-link">
                  Service Details
                </a>
              </li>
            </ul>
          </li>

          <li class="nav-item">
            <a href="#" class="nav-link">
              Blog
              <i class="bx bx-plus"></i>
            </a>
            <ul class="dropdown-menu">
              <li class="nav-item">
                <a href="blog.html" class="nav-link"> Blog </a>
              </li>
              <li class="nav-item">
                <a href="blog-details.html" class="nav-link"> Blog Details </a>
              </li>
            </ul>
          </li>
          <li class="nav-item">
            <a href="contact.html" class="nav-link"> Contact </a>
          </li>
        </ul>

        <div class="side-nav d-in-line align-items-center">
          <div class="side-item">
            <div class="search-box">
              <i class="flaticon-loupe"></i>
            </div>
          </div>

          <div class="side-item">
            <div class="user-btn">
              <a href="#">
                <i class="flaticon-contact"></i>
              </a>
            </div>
          </div>

          <div class="side-item">
            <div class="nav-add-btn">
              <a href="#" class="nav-menu-btn">
                Contact us
                <i class="bx bx-plus"></i>
              </a>
            </div>
          </div>
        </div>
      </div>
    </nav>
  </div>
</div>

<div class="side-nav-responsive">
  <div class="container">
    <div class="dot-menu">
      <div class="circle-inner">
        <div class="circle circle-one"></div>
        <div class="circle circle-two"></div>
        <div class="circle circle-three"></div>
      </div>
    </div>

    <div class="container">
      <div class="side-nav-inner">
        <div class="side-nav justify-content-center align-items-center">
          <div class="side-item">
            <div class="search-box">
              <i class="flaticon-loupe"></i>
            </div>
          </div>

          <div class="side-item">
            <div class="user-btn">
              <a href="#">
                <i class="flaticon-contact"></i>
              </a>
            </div>
          </div>

          <div class="side-item">
            <div class="nav-add-btn">
              <a href="#" class="nav-menu-btn border-radius">
                Contact us
                <i class="bx bx-plus"></i>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/base/preloader.html
{% extends "base/base.html" %} {% load static %} {% block preloader %}
<!-- Pre Loader -->
<div class="preloader">
  <div class="d-table">
    <div class="d-table-cell">
      <div class="spinner"></div>
    </div>
  </div>
</div>
<!-- End Pre Loader -->

{% endblock %}